Fix Pylint
Wilreyyt/FirstTry pull request #1
Opened 2024-05-05 15:00 UTC by Wilreyyt

2024-05-05 15:48 UTC, Stml89 requested changes
Please, fix lenters and PR name

2024-05-07 18:34 UTC, Stml89 commented
nice, only Pull request name is left to correct

2024-05-09 17:51 UTC, Wilreyyt commented
Any info?

2024-05-09 18:54 UTC, Stml89 approved these changes
You can merge it to master

2024-05-09 20:04 UTC, merged