Homework7: Lazar Maxim
Wilreyyt/FirstTry pull request #5
Opened 2024-05-25 12:01 UTC by Wilreyyt

2024-05-28 21:06 UTC, Stml89 requested changes

2024-05-28 21:06 UTC, Stml89 commented on homework_7/cows_and_bulls.py
Everything in uppercase? Pls, use letters in the lowercase

2024-05-28 21:06 UTC, Stml89 commented on homework_7/cows_and_bulls.py
> +    INPUT_NUMBER = input("Введите ваше 4-значное число: ")
user still can enter non unique number

2024-05-28 21:06 UTC, Stml89 commented on homework_7/statues.py
> +STATUES.sort()
you do not need to sort, the easiest way is to get min() and max() values and iterate from min to max

2024-05-29 19:58 UTC, Wilreyyt commented
It's done

2024-05-29 21:13 UTC, Stml89 approved these changes

2024-05-30 04:52 UTC, merged